require('dotenv').config();
const express=require('express'),http=require('http'),path=require('path'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs');
const{Server}=require('socket.io');const{v4:uuid}=require('uuid');
const app=express(),server=http.createServer(app);
const io=new Server(server,{cors:{origin:'*'},transports:['polling'],pingTimeout:60000,pingInterval:25000});
app.use(express.json());app.set('trust proxy',1);app.use(express.static(path.join(__dirname,'../public')));
const JWT_SECRET=process.env.JWT_SECRET||'dev_secret',ADMIN_EMAIL=process.env.ADMIN_EMAIL||'gustavenglund69@gmail.com',ADMIN_PIN=process.env.ADMIN_PIN||'5693';
const users=new Map(),emails=new Map(),mods=new Set(),muted=new Set(),banned=new Set(),adminSessions=new Set(),online=new Map(),calls=new Map(),games=new Map();
const rooms=new Map([['general',{id:'general',name:'General',private:false,ownerId:null,messages:[],members:new Set()}]]);
const sign=u=>jwt.sign({id:u.id},JWT_SECRET,{expiresIn:'30d'}),verify=t=>{try{return jwt.verify(t,JWT_SECRET)}catch{return null}};
const role=u=>!u?'user':(u.email===ADMIN_EMAIL||adminSessions.has(u.id))?'admin':mods.has(u.id)?'moderator':'user';
const safe=u=>({id:u.id,username:u.username,email:u.email,avatar:u.avatar,picture:u.picture,anon:!!u.anon,role:role(u),theme:u.theme||'midnight',muted:muted.has(u.id),banned:u.email?banned.has(u.email):false});
const reqUser=req=>{const d=verify(req.headers.authorization?.split(' ')[1]);return d?users.get(d.id):null};
const needAdmin=(req,res,next)=>{const u=reqUser(req);if(!u)return res.status(401).json({error:'Unauthorized'});if(role(u)!=='admin')return res.status(403).json({error:'Admin only'});req.user=u;next()};
const needMod=(req,res,next)=>{const u=reqUser(req);if(!u)return res.status(401).json({error:'Unauthorized'});if(!['admin','moderator'].includes(role(u)))return res.status(403).json({error:'Mod only'});req.user=u;next()};
app.post('/api/auth/register',async(req,res)=>{const username=String(req.body.username||'').trim(),email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!username||!email||password.length<6)return res.status(400).json({error:'Fill in all fields'});if(emails.has(email))return res.status(400).json({error:'Email exists'});const u={id:uuid(),username,email,avatar:username[0].toUpperCase(),passwordHash:await bcrypt.hash(password,10),theme:'midnight'};users.set(u.id,u);emails.set(email,u.id);res.json({token:sign(u),user:safe(u)})});
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),u=users.get(emails.get(email));if(!u||!await bcrypt.compare(String(req.body.password||''),u.passwordHash||''))return res.status(401).json({error:'Invalid login'});if(banned.has(email))return res.status(403).json({error:'Banned'});res.json({token:sign(u),user:safe(u)})});
app.post('/api/auth/anonymous',(req,res)=>{const username=String(req.body.username||'').trim();if(username.length<2)return res.status(400).json({error:'Enter a name'});const u={id:'anon_'+uuid(),username,email:null,avatar:username[0].toUpperCase(),anon:true,theme:'midnight'};users.set(u.id,u);res.json({token:sign(u),user:safe(u)})});
app.post('/api/auth/google',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),name=String(req.body.name||'Google User').trim();if(!email)return res.status(400).json({error:'Invalid Google'});let u=users.get(emails.get(email));if(!u){u={id:'google_'+String(req.body.googleId||uuid()),username:name,email,avatar:name[0].toUpperCase(),picture:req.body.picture,theme:'midnight'};users.set(u.id,u);emails.set(email,u.id)}res.json({token:sign(u),user:safe(u)})});
app.post('/api/user/theme',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({error:'Unauthorized'});u.theme=String(req.body.theme||'midnight');res.json({success:true,user:safe(u)})});
app.post('/api/admin/unlock-pin',(req,res)=>{const u=reqUser(req);if(!u)return res.status(401).json({error:'Login first'});if(String(req.body.pin)!==ADMIN_PIN)return res.status(403).json({error:'Wrong PIN'});adminSessions.add(u.id);res.json({success:true,user:safe(u)})});
app.get('/api/rooms',(req,res)=>res.json([...rooms.values()].filter(r=>!r.private).map(r=>({id:r.id,name:r.name,private:r.private,memberCount:r.members.size}))));
app.get('/api/admin/stats',needMod,(req,res)=>res.json({totalUsers:users.size,onlineUsers:online.size,totalRooms:rooms.size,totalMessages:[...rooms.values()].reduce((a,r)=>a+r.messages.length,0),games:games.size,muted:muted.size,mods:mods.size}));
app.get('/api/admin/users',needAdmin,(req,res)=>res.json([...users.values()].map(safe)));
app.get('/api/admin/rooms',needAdmin,(req,res)=>res.json([...rooms.values()].map(r=>({id:r.id,name:r.name,private:r.private,memberCount:r.members.size,messageCount:r.messages.length}))));
app.post('/api/admin/mute',needMod,(req,res)=>{muted.add(req.body.userId);res.json({success:true})});app.post('/api/admin/unmute',needMod,(req,res)=>{muted.delete(req.body.userId);res.json({success:true})});
app.post('/api/admin/kick',needMod,(req,res)=>{kick(req.body.userId,'You were kicked');res.json({success:true})});app.post('/api/admin/ban',needMod,(req,res)=>{const u=users.get(req.body.userId);if(u?.email)banned.add(u.email);kick(req.body.userId,'You were banned');res.json({success:true})});
app.post('/api/admin/add-mod',needAdmin,(req,res)=>{mods.add(req.body.userId);res.json({success:true})});app.post('/api/admin/remove-mod',needAdmin,(req,res)=>{mods.delete(req.body.userId);res.json({success:true})});
app.post('/api/admin/clear-room',needMod,(req,res)=>{const r=rooms.get(req.body.roomId);if(r)r.messages=[];io.to(req.body.roomId).emit('room_cleared');res.json({success:true})});
io.use((s,n)=>{const d=verify(s.handshake.auth.token),u=d?users.get(d.id):null;if(!u)return n(new Error('Unauthorized'));s.userFull=u;s.user=safe(u);n()});
io.on('connection',s=>{const u=s.userFull;online.set(s.id,{userId:u.id,roomId:null});io.emit('online_count',online.size);
s.on('join_room',id=>{const r=rooms.get(id);if(!r)return;s.join(id);leaveRoom(s);r.members.add(s.id);online.get(s.id).roomId=id;s.emit('room_history',r.messages.slice(-100));io.to(id).emit('room_members',members(id))});
s.on('create_room',d=>{const name=String(d.name||'').trim().slice(0,32);if(name.length<2)return s.emit('error_msg','Room name too short');const r={id:uuid().slice(0,8),name,private:!!d.private,ownerId:u.id,messages:[],members:new Set()};rooms.set(r.id,r);io.emit('rooms_updated');s.emit('room_created',{id:r.id,name:r.name,private:r.private})});
s.on('send_message',d=>{const r=rooms.get(d.roomId),content=String(d.content||'').trim().slice(0,500);if(!r||!content||muted.has(u.id))return;const m={id:uuid(),userId:u.id,username:u.username,avatar:u.avatar,content,timestamp:Date.now(),roomId:r.id,role:role(u)};r.messages.push(m);if(r.messages.length>300)r.messages.shift();io.to(r.id).emit('new_message',m)});
s.on('typing',d=>s.to(d.roomId).emit('user_typing',{username:u.username,typing:!!d.typing}));s.on('mod_delete_message',d=>{if(!['admin','moderator'].includes(role(u)))return;const r=rooms.get(d.roomId);if(r)r.messages=r.messages.filter(m=>m.id!==d.messageId);io.to(d.roomId).emit('message_deleted',{messageId:d.messageId})});
s.on('call_join',d=>{const id=String(d.callId||'general');if(!calls.has(id))calls.set(id,new Set());const peers=[...calls.get(id)];calls.get(id).add(s.id);s.join('call_'+id);peers.forEach(p=>io.to(p).emit('call_peer_joined',{peerId:s.id,username:u.username}));s.emit('call_existing_peers',{peers,callId:id})});
s.on('call_offer',d=>io.to(d.to).emit('call_offer',{from:s.id,offer:d.offer,username:u.username}));s.on('call_answer',d=>io.to(d.to).emit('call_answer',{from:s.id,answer:d.answer}));s.on('call_ice',d=>io.to(d.to).emit('call_ice',{from:s.id,candidate:d.candidate}));s.on('call_leave',d=>leaveCall(s,d.callId));
s.on('game_create',d=>{const g=createGame(d.type,u);games.set(g.id,g);s.join('game_'+g.id);s.emit('game_created',{game:g})});s.on('game_join',d=>{const g=games.get(String(d.gameId||'').toUpperCase());if(!g)return s.emit('game_error','Game not found');if(g.players.length>=2)return s.emit('game_error','Game full');g.players.push({id:u.id,username:u.username});g.status='playing';s.join('game_'+g.id);io.to('game_'+g.id).emit('game_updated',g)});
s.on('game_move',d=>{const g=games.get(d.gameId);if(!g)return;const e=move(g,d.move,u.id);if(e)return s.emit('game_error',e);io.to('game_'+g.id).emit('game_updated',g)});s.on('disconnect',()=>{leaveRoom(s);calls.forEach((_,id)=>leaveCall(s,id));online.delete(s.id);io.emit('online_count',online.size)})});
function kick(id,reason){for(const[sid,i]of online)if(i.userId===id)io.to(sid).emit('force_logout',{reason})}function leaveRoom(s){const i=online.get(s.id);if(!i?.roomId)return;rooms.get(i.roomId)?.members.delete(s.id);io.to(i.roomId).emit('room_members',members(i.roomId));s.leave(i.roomId);i.roomId=null}function members(id){return[...(rooms.get(id)?.members||[])].map(sid=>users.get(online.get(sid)?.userId)).filter(Boolean).map(safe)}function leaveCall(s,id){const set=calls.get(id);if(!set)return;set.delete(s.id);s.leave('call_'+id);io.to('call_'+id).emit('call_peer_left',{peerId:s.id});if(!set.size)calls.delete(id)}
function createGame(type,u){const id=uuid().slice(0,6).toUpperCase(),base={id,type,players:[{id:u.id,username:u.username}],status:'waiting',turn:0,winner:null};if(type==='connect4')return{...base,board:Array(42).fill(null)};if(type==='rps')return{...base,choices:{}};if(type==='memory'){let board=[...Array(8).keys(),...Array(8).keys()].sort(()=>Math.random()-.5);return{...base,board,flipped:[],matched:[],scores:[0,0]}}return{...base,type:'tictactoe',board:Array(9).fill(null)}}
function move(g,m,uid){const p=g.players.findIndex(x=>x.id===uid);if(p<0)return'Not a player';if(g.status!=='playing')return'Game not active';if(g.type==='rps'){g.choices[uid]=m.choice;if(Object.keys(g.choices).length===2){const a=g.choices[g.players[0].id],b=g.choices[g.players[1].id];g.winner=a===b?'draw':(a==='rock'&&b==='scissors'||a==='paper'&&b==='rock'||a==='scissors'&&b==='paper')?0:1;g.status='ended'}return null}if(g.turn%2!==p)return'Not your turn';if(g.type==='connect4'){let c=+m.col,row=-1;for(let r=5;r>=0;r--)if(g.board[r*7+c]===null){row=r;break}if(row<0)return'Column full';g.board[row*7+c]=p;g.turn++;if(win4(g.board,row,c,p)){g.winner=p;g.status='ended'}else if(g.turn>=42){g.winner='draw';g.status='ended'}return null}if(g.type==='memory'){let i=+m.index;if(g.matched.includes(i)||g.flipped.includes(i))return'Invalid';g.flipped.push(i);if(g.flipped.length===2){const[a,b]=g.flipped;if(g.board[a]===g.board[b]){g.matched.push(a,b);g.scores[p]++;if(g.matched.length===g.board.length){g.winner=g.scores[0]===g.scores[1]?'draw':g.scores[0]>g.scores[1]?0:1;g.status='ended'}}else g.turn++;setTimeout(()=>{g.flipped=[];io.to('game_'+g.id).emit('game_updated',g)},900)}return null}let i=+m.index;if(g.board[i]!==null)return'Taken';g.board[i]=p;g.turn++;let w=win3(g.board);if(w!==null){g.winner=w;g.status='ended'}else if(g.turn>=9){g.winner='draw';g.status='ended'}return null}
function win3(b){for(const l of[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[l[0]]!==null&&b[l[0]]===b[l[1]]&&b[l[0]]===b[l[2]])return b[l[0]];return null}function win4(b,r,c,p){for(const[dR,dC]of[[0,1],[1,0],[1,1],[1,-1]]){let n=1;for(let d=1;d<4;d++){let rr=r+dR*d,cc=c+dC*d;if(rr<0||rr>5||cc<0||cc>6||b[rr*7+cc]!==p)break;n++}for(let d=1;d<4;d++){let rr=r-dR*d,cc=c-dC*d;if(rr<0||rr>5||cc<0||cc>6||b[rr*7+cc]!==p)break;n++}if(n>=4)return true}return false}
server.listen(process.env.PORT||3000,()=>console.log('Nexus Chat App running'));
